Overall-dashboard Works
Elliott03/UCReviews pull request #46
Opened 2024-10-21 16:43 UTC by pratxks

Made the Overall-dashboard!

2024-10-21 19:45 UTC, whsiq approved these changes

2024-10-21 20:26 UTC, artulloss requested changes
Overall good, please move images out of git.

2024-10-21 20:26 UTC, artulloss commented on web-client/src/assets/overall-dashboard-images/dining-halls.jpg
Remove and put in the wwwroot folder please.

2024-10-21 20:26 UTC, artulloss commented on web-client/src/assets/overall-dashboard-images/housing.jpg
Remove and put in the wwwroot folder please.

2024-10-21 20:26 UTC, artulloss commented on web-client/src/assets/overall-dashboard-images/parking.jpg
Remove and put in the wwwroot folder please.

2024-10-21 20:26 UTC, artulloss commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +        <img src="assets/overall-dashboard-images/{{category.image}}" class="image" />
Use our wwwroot folder here.

2024-10-21 20:38 UTC, Elliott03 commented
Those wwwroot changes are my bad. For some reason I said to put the images in the client, but i don't remember why. wwwroot is definitely better. Just send the new folder in teams

2024-10-21 20:40 UTC, Elliott03 commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
There is new control flow syntax that deprecates ngFor: https://angular.dev/guide/templates/control-flow

2024-10-21 20:42 UTC, Elliott03 commented on web-client/src/app/overall-dashboard/overall-dashboard.component.ts
> +    console.log(`${category.name} clicked!`);
We can probably get rid of the console.log

2024-10-21 20:45 UTC, Elliott03 commented on web-client/src/app/overall-dashboard/overall-dashboard.component.ts
> +  categories = [
I don't think this is blocking, but it would probably make sense to use a typescript model for each individual category

2024-10-22 01:00 UTC, pratxks commented on web-client/src/app/overall-dashboard/overall-dashboard.component.ts
> +  categories = [
makes sense- just updated it!

2024-10-22 01:00 UTC, pratxks commented on web-client/src/app/overall-dashboard/overall-dashboard.component.ts
> +    console.log(`${category.name} clicked!`);
done!

2024-10-22 01:01 UTC, pratxks commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +        <img src="assets/overall-dashboard-images/{{category.image}}" class="image" />
Done!

2024-10-22 01:01 UTC, pratxks commented on web-client/src/assets/overall-dashboard-images/parking.jpg
Done!

2024-10-22 01:01 UTC, pratxks commented on web-client/src/assets/overall-dashboard-images/housing.jpg
Done!

2024-10-22 01:01 UTC, pratxks commented on web-client/src/assets/overall-dashboard-images/dining-halls.jpg
Done!

2024-10-22 01:11 UTC, Elliott03 commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
My bad I should have been more clear. It should be the part that looks like 
`@for (item of items; track item.id) {
  {{ item.name }}
}`

2024-10-22 01:25 UTC, pratxks commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
No worries at all! I appreciate the clarification. I’m still getting familiar with Angular, so thanks for your guidance!

2024-10-22 01:25 UTC, pratxks commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
Just went ahead and pushed the changes!

2024-10-22 01:41 UTC, Elliott03 commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
I'm mostly talking about the ng-container. It should be able to be replaced. So 
`<ng-container *ngFor="let category of categories">
    <div class="inline-card">
      <mat-card class="card" (click)="categoryClick(category)">
        <img src="/api/Images/overall-dashboard-images/{{category.image}}" class="image" />
        <div class="info">
          <h2 class="name">{{category.name}}</h2>
          <div class="style-cost">
            <h3 class="description">{{category.description}}</h3>
          </div>
          <button mat-flat-button>View</button>
        </div>
      </mat-card>
    </div>
  </ng-container>` 
should be replaced with something like 
`
@for(category of categories;  track category.id)
    <div class="inline-card">
      <mat-card class="card" (click)="categoryClick(category)">
        <img src="/api/Images/overall-dashboard-images/{{category.image}}" class="image" />
        <div class="info">
          <h2 class="name">{{category.name}}</h2>
          <div class="style-cost">
            <h3 class="description">{{category.description}}</h3>
          </div>
          <button mat-flat-button>View</button>
        </div>
      </mat-card>
    </div>
  }

2024-10-22 01:42 UTC, Elliott03 commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
Idk why that got formatted so weirdly. But the only difference is that <ng-container> is replaced with the `@for`loop

2024-10-22 02:01 UTC, pratxks commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
Thanks! just pushed changes, let me know if that's good!

2024-10-22 02:02 UTC, Elliott03 approved these changes

2024-10-22 02:03 UTC, Elliott03 commented on web-client/src/app/overall-dashboard/overall-dashboard.component.html
> +    <div class="inline-card" *ngFor="let category of categories">
looks good

2024-10-23 01:13 UTC, artulloss approved these changes

2024-10-23 01:13 UTC, merged